spring.main.sources: dk.dma.enav.integrations.ForecastInRouter

server.port: 9080

logging:
  file: ${user.home}/arcticweb/ForecastIn/logging/forecastIn.log

---
spring:
  profiles: unittest

logging:
  file: ${user.home}/arcticweb/ForecastIn/logging/forecastIn-test.log