spring.main.sources: dk.dma.enav.integrations.ForecastInRouter

server.port: 9080

logging:
  file: target/logging/forecastIn.log

---
spring:
  profiles: unittest

logging:
  file: target/logging/forecastIn-test.log